### ISSUE TITLE
uWSGI

### ISSUE THREAD

**Issue by ghost** [bretth/woven#18]
modwsgi with Apache isn't as nice as uWSGI (to complex, slow compared to uWSGI).

Actually we could get rid of Apache altogether by just using Nginx and uwsgi:
- http://projects.unbit.it/uwsgi/
- http://blog.zacharyvoase.com/2010/02/03/django-project-conventions/
- http://blog.zacharyvoase.com/2010/03/05/django-uwsgi-nginx/

**Comment by bretth** [comment]
Please see my new ticket #19.
